import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Silkyester | Terms",
  description: "Silkyester Terms and Conditions",
};

const Page = () => {
  return (
    <div className="max-w-desktop mx-auto p-6 my-10 select-text">
      <h1 className="text-3xl font-bold text-center mb-6">Terms of Service</h1>
      <p className="mb-6">
        This website (
        <a href="https://www.silkyester.com" className="text-blue-600 hover:underline">
          www.silkyester.com
        </a>
        ) is operated by Silkyester. The terms "we," "our," and "us" refer to Silkyester, which is registered at the
        following address:
      </p>
      <p className="mb-6">
        Floor No.: 00, Building No./Flat No.: Tehsil Moradabad, Premises Name: C/O Shri Radesh Kumar, Street: OD 040104,
        Nearest Landmark: Panchayat Headquarter, Locality/Sub-locality: Post Gatora, City/Town/Village: Mohammadpur,
        District: Moradabad, State: Uttar Pradesh, 240001.
      </p>
      <p className="mb-6">
        We provide all the information, tools, and services through this website, which are subject to the acceptance of the
        following terms, conditions, policies, and notices.
      </p>
      <p className="mb-6">
        This is an electronic record generated by a computer system and does not require any physical or digital signatures.
      </p>
      <p className="mb-6">
        When you visit our site and/or purchase our products, you engage in our "service" and agree to the following terms
        and conditions ("Terms of Service" or "Terms"), including any additional terms and policies referenced herein. These
        Terms of Service apply to all users of the site, including browsers, vendors, customers, merchants, and/or content
        contributors.
      </p>
      <p className="mb-6">
        Please read our Terms of Service carefully before using our website. By accessing or using the site, you agree to be
        bound by these Terms of Service. If you do not agree to these Terms and Conditions, you may not access the website or
        use any services.
      </p>
      <p className="mb-6">
        Any new features or tools added to the current store will also be subject to the Terms of Service. You can always
        review the latest version of the Terms of Service. We reserve the right to update, change, or modify these Terms from
        time to time. We will notify you of any changes. Using or accessing the website after any changes are posted will
        signify your acceptance of those changes.
      </p>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Online Store Terms</h2>
        <p className="mb-4">
          By agreeing to the Terms of Service, you declare that you are a resident of your state or province, or you are a
          resident of your state or province and have consented to allow any minor children of yours to use this site.
        </p>
        <p className="mb-4">
          You may not use our products for any unlawful or unauthorized purpose, nor may you violate any laws (including
          copyright laws) in your use of the service. You must not transmit any viruses, worms, or any other harmful code.
        </p>
        <p className="mb-4">
          Users can register on the website and create an account to order any products or avail of services. You may choose
          to delete your account at any time. However, we may retain your registration details as long as required by
          applicable laws. You are fully responsible for maintaining the confidentiality of your account and password, and
          for all activities that occur under your account. We are not responsible for any loss or damage that may occur due
          to failure to secure your account or password. You should take all necessary steps to ensure that your password
          remains confidential and secure.
        </p>
        <p className="mb-4">Any violation of these terms may result in immediate termination of your services.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">General Terms</h2>
        <p className="mb-4">We reserve the right to refuse service to anyone at any time, for any reason.</p>
        <p className="mb-4">
          You understand that your content/information (excluding credit card information) may be transferred unencrypted and
          involve (a) transmissions over various networks; and (b) changes and adaptations to meet technical requirements of
          connecting networks or devices. Credit card information is always encrypted during transmission over networks.
        </p>
        <p className="mb-4">
          You agree not to reproduce, duplicate, copy, sell, resell, or exploit any portion of the service, use of the
          service, or access to the service, without our explicit written permission.
        </p>
        <p className="mb-4">
          The headings used in this agreement are for convenience only and do not affect or limit these Terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Accuracy, Completeness, and Timeliness of Information</h2>
        <p className="mb-4">
          We are not responsible if the information available on this site is not accurate, complete, or up-to-date. The
          content on this site is provided for general information purposes only and should not be relied upon as the sole
          basis for making decisions. You should consult primary, more accurate, more complete, or more timely sources of
          information. Any reliance on the material on this site is at your own risk.
        </p>
        <p className="mb-4">
          This site may also contain historical information. Historical information is, by nature, not current and is
          provided only for your reference. We reserve the right to modify the content on this site, but we are not obligated
          to update any information on the site.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Service and Price Modifications</h2>
        <p className="mb-4">
          Prices for our products may change without notice. We also reserve the right to modify or discontinue the service
          (or any part or content thereof) without notice. We will not be liable to you or any third party for any
          modifications, price changes, suspensions, or discontinuation of the service.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Products or Services</h2>
        <p className="mb-4">
          Some products or services may be available exclusively through the online website. These products or services may
          have limited quantities and are subject to return or exchange only in accordance with our Return Policy.
        </p>
        <p className="mb-4">
          We have made every effort to display the colors and images of our products as accurately as possible. However, we
          cannot guarantee that the display on your computer monitor will be accurate.
        </p>
        <p className="mb-4">
          We reserve the right, but are not obligated, to limit the sales of our products or services to any person,
          geographic region, or jurisdiction. We may exercise this right on a case-by-case basis. We also reserve the right
          to limit the quantities of any products or services we offer.
        </p>
        <p className="mb-4">
          We reserve the right to change any product or service descriptions or prices without notice. We may discontinue any
          product at any time. Any offer for any product or service made on this site is void where prohibited.
        </p>
        <p className="mb-4">
          We do not guarantee that the quality of any products, services, information, or other materials purchased or
          obtained by you will meet your expectations.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Billing and Account Information Accuracy</h2>
        <p className="mb-4">
          We reserve the right to refuse any order you place with us. We may, at our sole discretion, limit or cancel
          quantities purchased per person, per household, or per order. These restrictions may include orders placed by or
          under the same customer account, the same credit card, and/or orders using the same billing and/or shipping
          address. If we make a change to or cancel an order, we will attempt to notify you by contacting the email address
          and/or billing address/phone number provided at the time the order was placed. We also reserve the right to limit
          or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers, or distributors.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Third-Party Tools</h2>
        <p className="mb-4">
          We may provide you with access to third-party tools over which we neither monitor nor have any control or input.
        </p>
        <p className="mb-4">
          You acknowledge and agree that we provide access to such tools "as is" and "as available" without any warranties,
          representations, or conditions of any kind. We shall have no liability whatsoever arising from or relating to your
          use of optional third-party tools.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Liability for Any Type of Damage</h2>
        <p className="mb-4">
          We will not be responsible for any kind of damage, loss, or harm arising from the use of any of our services or
          products, whether direct, indirect, consequential, or special. This means that if you suffer any loss as a result
          of any action you take, it will not be our responsibility.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Legal Disputes and Jurisdiction</h2>
        <p className="mb-4">
          Any dispute arising under these Terms of Service will be resolved in the courts of Moradabad, Uttar Pradesh. Indian
          law will apply to such disputes.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Consent and Acceptance of Terms</h2>
        <p className="mb-4">
          You understand and agree that you will use our website in accordance with these Terms. If you disagree with any of
          these terms, you should not use the website.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Third-Party Links</h2>
        <p className="mb-4">
          There may be links on our website that point to third-party websites or resources. These links are provided for
          convenience and informational purposes only. We are not responsible for the content, products, or services of these
          websites or resources, nor do we make any guarantees about them.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Changes to the Service</h2>
        <p className="mb-4">
          We reserve the right to change or remove any services, features, or products on our website without prior notice.
          Using the website after such changes will be considered as your acceptance of the changes.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Privacy Policy</h2>
        <p className="mb-4">
          The security of your personal information is our priority, and we collect and use it in a confidential manner. For
          more information about our privacy practices, you can read our Privacy Policy, which is available on this website.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Product Return and Refund</h2>
        <p className="mb-4">
          Our return and refund policy applies to purchases made on our website. If you wish to return a product, you must
          follow our return policy, which is available on this website.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Age Limit</h2>
        <p className="mb-4">
          To use our website, you must be at least 18 years old. If you are under 18, you must obtain permission from your
          parents or legal guardian to use our services.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Account Security</h2>
        <p className="mb-4">
          If you have created an account on our website, you are responsible for ensuring its security and confidentiality.
          You will ensure that your account and password are secure, and you will not share your account information.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">User-Generated Content</h2>
        <p className="mb-4">
          Any content you upload or post on our website, such as comments, reviews, or other content, will be your
          responsibility. We are not liable for any offensive, illegal, or inappropriate content. You agree to use your
          content solely for legal purposes.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Privacy and Security</h2>
        <p className="mb-4">
          We keep your personal information confidential and take reasonable steps to secure it. However, data transmission
          over the internet cannot be completely secure, and we will not be responsible for any security breaches.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Termination and Suspension</h2>
        <p className="mb-4">
          We reserve the right to terminate or suspend any user’s account if we find that they have violated our terms of
          service. We will not be responsible for providing prior notice for such suspension or termination.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Legal Consent and Amendment of Terms</h2>
        <p className="mb-4">
          We may make changes to our terms of service at any time. In such cases, we will update it on the website. You
          should stay informed of these changes and accept the new terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Our Responsibility and Limitations</h2>
        <p className="mb-4">
          We do not guarantee the accuracy and completeness of the content on our website. We provide general information and
          services only. We will not be responsible for any technical, data, or financial loss that may occur for any reason.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Use of Website</h2>
        <p className="mb-4">
          To use our website, you must agree to our terms and conditions. By using this website, you fully accept our terms
          of service, and all your activities will be subject to these terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Terms of Service</h2>
        <p className="mb-4">
          Our service may only be used for lawful and legal purposes. You will not use our service for any illegal, abusive,
          fraudulent, or any other activities that violate our terms and conditions.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Account Security and Privacy</h2>
        <p className="mb-4">
          If you create an account on our website, you must ensure that you keep your account information secure and not
          share it with any third party. You will be fully responsible for your account information and will take necessary
          steps to prevent unauthorized use.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">User-Generated Content</h2>
        <p className="mb-4">
          Any content you upload, post, or publish on our website, such as comments, reviews, blog posts, etc., will be your
          responsibility. You must ensure that your content is not illegal, abusive, or unethical in any way. We will not be
          responsible for any offensive or inappropriate content. You agree to use your content solely for legal purposes.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Limitation of Liability</h2>
        <p className="mb-4">
          Our website is provided on an “as is” and “as available” basis. We will not be liable for any indirect, incidental,
          special, or consequential damages arising out of or in connection with your use of our website.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Governing Law and Jurisdiction</h2>
        <p className="mb-4">
          These terms of service are governed by and construed in accordance with the laws of Moradabad, Uttar Pradesh,
          India. Any disputes arising out of or in connection with these terms will be subject to the exclusive jurisdiction
          of the courts in Moradabad, Uttar Pradesh, India.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Acceptance of Terms</h2>
        <p className="mb-4">
          By using our website, you agree to be bound by these terms of service. If you do not agree to these terms, please
          do not use our website.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Changes to Terms</h2>
        <p className="mb-4">
          We reserve the right to modify or update these terms of service at any time. Any changes will be effective
          immediately upon posting the updated terms on our website.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Entire Agreement</h2>
        <p className="mb-4">
          These terms of service constitute the entire agreement between you and our website. If any provision of these terms
          is found to be invalid or unenforceable, the remaining provisions will remain in full force and effect.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Severability</h2>
        <p className="mb-4">
          If any provision of these terms is found to be invalid or unenforceable, the remaining provisions will remain in
          full force and effect. However, if a provision is found to be invalid or unenforceable, the entire agreement will
          be null and void.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Waiver</h2>
        <p className="mb-4">
          No waiver of any term of these terms will be deemed a further or continuing waiver of such term or any other term
          or condition, and all such waivers shall be null and void.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
        <p className="mb-4">If you have any questions or concerns about our terms of service, please contact us at:</p>
        <p className="mb-4">
          Email:{" "}
          <Link className="text-blue-600 hover:underline" href="mailto:policy@silkyester.com">
            policy@silkyester.com
          </Link>
        </p>
      </section>
    </div>
  );
};

export default Page;
